
const levels = {
	1: [
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o  xxxxxxxxxxxxxxxxxxxxxxxxxx  xxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o',
		'o  xxxxxxxxxxxxxxxxxxxxxxxxxx  xxx                                                          xxxxx  o',
		'o  xxxxxxxxxxxxxxxxxxxxxxxxxx  xxx                                                          xxxxx  o',
		'o  xxxxxxxxxxxxxxxxxxxxxxxxxx  xxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxx  o',
		'o  xxx                         xxx  xxxxxxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxx                         xxx  xxxxxxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxx                         xx   xxxxxxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxx                        xx     xxxxxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxx                       xx       xxxxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxx                     xx         xxxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxx                  xxx           xxxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxx                xxx             xxxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxx              xxx               xxxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxx            xxx                 xxxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxx          xxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxx         xxx                                                           xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxx        xxx                                                           xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx       xxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx       xxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                                                           xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxx  x   xxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o  xxxxxxxxxxxxx x  xxxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxxx x  xxxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o  xxxxxxxxxxxxx x  xxxxx                   xxxxxxxxxxxxxxx                         xxxxxx  xxxxx  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
	],

	2: [
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o  xxxxxxxxxxxxxx    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx                o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
	],

	3: [
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxx   xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxx                                                xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxx            xxxxxxxxxxxxxxxxxxxxxxxx    xxxxx        xxxxxxxxxxxxxx            xxxxxxx    xo',
		'o   xxxx                              xxxxxx            xxxx xxxxxxxxx            xxxxxxx          o',
		'o   xxxx              xxxxxxxxxxxxxxx xxxxxx   xxxxx         xxxxxxxxx xxxx            xxxxxxx    xo',
		'o   xxxx                         xxxx xxxxxx            xxxxxxxxxxxxxx            xxxxxxx          o',
		'o   xxxx                         xxxx xxxxxx   xxxxx         xxxxxxxxxxxxxx            xxxxxxx    xo',
		'o   xxxx                         xxxx xxxxxx            xxxx xxxxxxxxx            xxxxxxx          o',
		'o   xxxx                         xxxx xxxxxx   xxxxx         xxxxxxxxx xxxx            xxxxxxx    xo',
		'o   xxxx                         xxxx xxxxxx            xxxxxxxxxxxxxx            xxxxxxx          o',
		'o   xxxx                         xxxx xxxxxx    xxxxx        xxxxxxxxxxxxxx            xxxxxxx    xo',
		'o   xxxx      xxxx xxxxxxxxxxxxxxxxxx xxxxxx            xxxx xxxxxxxxx            xxxxxxx          o',
		'o   xxxx      xxxx xxxxxxxxxxxxxxxxxx xxxxxx   xxxxx         xxxxxxxxx xxxx            xxxxxxx    xo',
		'o   xxxx      xxxx                    xxxxxx            xxxxxxxxxxxxxx            xxxxxxx          o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx         xxxxxxxxxxxxxx            xxxxxxx    xo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o  xxxxxxxxxxxx x    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxxxo',
		'o  xxxxxxxx   x x    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxx o',
		'o  x      x x x x    xxxxxx             xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxxxo',
		'o  x xxxx x x x x    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxx o',
		'o  x    x x x x x    xxxxxx  xxxxxxxxxx xxxxxxxx                        xxxxxxxxxxx  xxxxxxxxxxxxxxo',
		'o  xxxx x x x x x    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxx o',
		'o  xx   x x x x x            xxxxxxxxxx          xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxxxo',
		'o  xx xxx   x   x    xxxxxx  xxxxxxxxxx          xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxx o',
		'o  xx xxxxxxxxxxx    xxxxxx  xxxxxxxxxx          xxxxxxxxxxxxxxx        xxxxxxxxxxx  xxxxxxxxxxxxxxo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxx xxxxxxxx xxxxxxxx    x  x     xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx  x        x xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx          xxxxxxxx      x  x   xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx   x  x  x   xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'oxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxx xxxxxxxxxxxxxo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xxxxx o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx          o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx                             xxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxx xxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxx                  xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxx                                      xxxxxxx          o',
		'o   xxxxxx xxxxx xxxxx                                  xxxxx   xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxx                                  xxxxx   xxxxxx            xxxxxxx    xx    o',
		'o          xxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx                                    xxxxx xxxxxx            xxxxxxx          o',
		'o   xxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxx xxxxxx            xxxxxxx    xxxxxxo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
	],

	4: [
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxx   xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxx                                                xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxx        xxxxxxxxxxxxxx            xxxxxxx    xo',
		'o   xxxx xxxx                         xxxxxx            xxxx xxxxxxxxx                             o',
		'o   xxxx xxxx xxxxxxxxxxxxxxxxxxxxxxx xxxxxx   xxxxx         xxxxxxxxx xxxx            xxxxxxx    xo',
		'o   xxxx xxxx x      x           xxxx xxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxx xxxx x xx      xxx                                                            xxxxxxx    xo',
		'o                                                       xxxx xxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxx xxxx x xx      xxx      xxxx xxxxxx   xxxxx         xxxxxxxxx xxxx            xxxxxxx    xo',
		'o   xxxx xxxx x xx   x      xxx  xxxx xxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxx xxxx xxxx  xxxxxxxxxxxxxxxx  xxxxxx   xxxxx         xxxxxxxxx xxxx            xxxxxxx    xo',
		'o   xxxx      xxxx                    xxxxxx            xxxxxxxxxxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx         xxxxxxxxxxxxxx            xxxxxxx    xo',
		'o                                                                                            xx    o',
		'o                                                                                            xx    o',
		'o   xxxxxxxxxxx x    xxxxxx  xxxxxxxxxx xxxxxxxx    xxx   x   xxxxxxxxxxxxxxx        xxxxxxxxxxx  xo',
		'o   xxxxxxx   x x    xxxxxx                                                          xxxxxxxxxxxxx o',
		'o                                                                                                  o',
		'o    xxxx x x x x    xxxxxx  xxxxxxxxxx xxxxxxxx xxxxxxxxxxxxxxx        xxxxxxxxxxx xxxxxxxxxxxxxx o',
		'o       x x x x x    xxxxxx  xxxxxxxxxx xxxxxxxx                        xxxxxxxxxxx  xxxxxxxxxxxxxxo',
		'o                                                                                                  o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o                                                                                                  o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o   xxxxx xxxxxxxx xxxxxxxx    x  x     xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx  x        x xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx          xxxxxxxx      x  x   xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx             xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o   xxxxx xxxxxxxx xxxxxxxx   x  x  x   xxxxxxxxxxxxxxx         xxxxx            xxxxx             o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'o                                                                                                  o',
		'oxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxx xxxxxxxxxxxxxo',
		'oxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxx xxxxxxxxxxxxxo',
		'oxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxx                                       xxxxxxxxx xxxxxxxxxxxxxo',
		'oxxxx                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx xxxxxxxxxxxxxo',
		'oxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxx xxxxxxxxxxxxxo',
		'o                                                                                                  o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xxxxx o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx          o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx                             xxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxx xxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxx                  xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxx                                      xxxxxxx          o',
		'o   xxxxxx xxxxx xxxxx                                  xxxxx   xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxx xxxxx xxxxx                                  xxxxx   xxxxxx            xxxxxxx    xx    o',
		'o          xxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx                                    xxxxx xxxxxx            xxxxxxx          o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxxxxxxxxxxxxx              xxxxx xxxxxx            xxxxxxx    xxxxxxo',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx                       xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o   xxxxxxxxxxxx xxxxx  xxxxxxxxx  xxxxxxxxx            xxxxxxx xxxxxx            xxxxxxx    xx    o',
		'o                                                       xxxxxxxxxxxxxx                             o',
		'o                                                       xxxxxxxxxxxxxx                             o',
		'o                                                                                                  o',
		'o                                                       xxxxxxxxxxxxxx                             o',
		'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
	]
}

export default levels;
